name: Deploy to EC2

on:
  push:
    branches:
      - main  # Run this workflow whenever code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC1P}}
          username: ${{ secrets.USER }}
          key: ${{ secrets.F }}
          script: |
            echo "Starting deployment on EC2..."
            cd /var/www/html
            sudo rm -f index.html
            sudo wget -O index.html https://raw.githubusercontent.com/${{ github.repository }}/main/index.html
            sudo systemctl restart apache2
            echo "Deployment complete!"
